import {test,expect,Page,Locator, chromium}from "@playwright/test"
test.skip("This is my second test",async()=>{
 const browser  =await chromium.launch()
 const browsercontext=await browser.newContext()
 const newpage=await browsercontext.newPage()
 await newpage.goto("https://ecommerce-playground.lambdatest.io/index.php?route=account/login")
 await newpage.locator("#input-email").fill("TomJohn@yopmail.com")
 await newpage.locator("#input-password").fill("Tom@1234")
 await newpage.locator("//input[@type='submit']").click()
 await newpage.waitForTimeout(20000)
 await browser.close()
})
test.skip("This is my third test",async()=>{
    test.setTimeout(10000000)
    const browser  =await chromium.launch()
    const browsercontext=await browser.newContext()
    const newpage=await browsercontext.newPage()
    await newpage.goto("https://ecommerce-playground.lambdatest.io/index.php?route=account/login")
    await newpage.locator("#input-email").fill("TomJohn@yopmail.com")
    await newpage.locator("#input-password").fill("Tom@1234")
    await newpage.locator("//input[@type='submit']").click()
    await newpage.waitForTimeout(10000)
    await newpage.goto("https://ecommerce-playground.lambdatest.io/index.php?route=account/login")
    await newpage.waitForTimeout(10000)
    const newpage2=await browsercontext.newPage()
    await newpage2.goto("https://chatgpt.com/")
    await newpage.waitForTimeout(10000)
    const newpage3=await browsercontext.newPage()
    await newpage3.goto("https://ecommerce-playground.lambdatest.io/index.php?route=account/login")
    await newpage.waitForTimeout(10000)
    await newpage3.goto("https://www.google.com")
    await newpage.waitForTimeout(10000)
   })
   test.skip("This is my fourth test",async()=>{
    const browser  =await chromium.launch()
    const browsercontext=await browser.newContext()
    const newpage=await browsercontext.newPage()
    await newpage.goto("https://ecommerce-playground.lambdatest.io/index.php?route=account/login")
    await newpage.waitForTimeout(10000)
    await browser.close()
   })

   test.skip("This is my six test",async({page})=>{
    //await page.setViewportSize({width:800,height: 800})
    await page.goto("https://news.google.com/home?hl=en-AU&gl=AU&ceid=AU:en")
    await page.waitForTimeout(10000)
    await page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=account/login")
    await page.locator("#input-email").fill("TomJohn@yopmail.com")
    await page.locator("#input-password").fill("Tom@1234")
    await page.locator("//input[@type='submit']").click()
    await page.waitForTimeout(5000)
    await page.goto("https://news.google.com/home?hl=en-AU&gl=AU&ceid=AU:en")
    
   })